name: publish-app-images
on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:
jobs:
  build_and_push_base_images:
    name: Build app base images
    strategy:
      matrix:
        app:
          - node-red
          - temporal-php
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ secrets.BOT_USER }}
          password: ${{ secrets.BOT_TOKEN }}

      - name: Build and push ${{ matrix.php-version }} to ghcr.io
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:${{ matrix.app }}"
          push: true
          file: Dockerfile
          build-args: |
              IMAGE_SOURCE=https://github.com/${{ github.repository }}
          tags: |
            ghcr.io/${{ github.repository_owner }}/app/${{ matrix.app }}:latest
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.BOT_TOKEN }}
